// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTI_4k_JnIW3AkjL-whoPcCclhRu-W-gQ',
    appId: '1:407369281226:android:855e7d37c8896cb7bd4e33',
    messagingSenderId: '407369281226',
    projectId: 'baseproj-727ec',
    storageBucket: 'baseproj-727ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV7jNlZD5g1880Z43S5ogC7nOGDBWS0NM',
    appId: '1:407369281226:ios:ddb25714e2c2b174bd4e33',
    messagingSenderId: '407369281226',
    projectId: 'baseproj-727ec',
    storageBucket: 'baseproj-727ec.appspot.com',
    iosClientId: '407369281226-kecuttbcl0opbafcro94umqeojpvknup.apps.googleusercontent.com',
    iosBundleId: 'com.example.userAuth2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV7jNlZD5g1880Z43S5ogC7nOGDBWS0NM',
    appId: '1:407369281226:ios:ddb25714e2c2b174bd4e33',
    messagingSenderId: '407369281226',
    projectId: 'baseproj-727ec',
    storageBucket: 'baseproj-727ec.appspot.com',
    iosClientId: '407369281226-kecuttbcl0opbafcro94umqeojpvknup.apps.googleusercontent.com',
    iosBundleId: 'com.example.userAuth2',
  );
}
